### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by crabdancing** [gega/csg2stp#2]
Not really clear. I understand the Makefile, but how does it integrate with the other repo mentioned in README.md?

**Comment by gega** [comment]
> Not really clear. I understand the Makefile, but how does it integrate with the other repo mentioned in README.md?

You should clone https://github.com/gega/OCC-CSG.git and choose the branch "sweep", compile and install (or put it in your personal bin). This is a modified version of OCC-CSG and this is needed for the generated makefile.
When this is ready, you can use the shell script from this repo (which will use OpenSCAD to generate .csg file from your .scad design) and the shell script will generate the makefile (using two utilities to convert csg to xml and xml to makefile) and the makefile can be run with a "make" command and it can do the regeneration of your design using OCC-CSG. The main reason of using makefile here is to enable easy parallel operation as the regeneration can takes a long time.
